Repository Kill-The-Data/NoNameSpecifiedByTeam, pull requests merged in 2020-06, with the labels that each got.

#148 made sure players can't spam space to get free stuff
  SpaceGame/Assets/Scripts/PlayerScripts/ScreenShake.cs
  SpaceGame/Assets/Scripts/PowerUps/CenterRotation.cs
  SpaceGame/Assets/Scripts/PowerUps/ItemSpawner.cs
  SpaceGame/Assets/Scripts/PowerUps/ShieldState.cs
  SpaceGame/Assets/Scripts/UI/ScoreUI.cs
  SpaceGame/deploy-version.txt
  SpaceGame/web-build/deploy-version.txt
  deploy-version.txt
Labels: WIP, bug, enhancement

#149 added prewarm system to level loading
  SpaceGame/Assets/Scripts/Debris/VoronoiDebrisGen.cs
  SpaceGame/Assets/Scripts/FSM/IngameState.cs
  SpaceGame/Assets/Scripts/FSM/IngameView.cs
  SpaceGame/Assets/Scripts/FSM/tutorial/TutorialState.cs
  SpaceGame/deploy-version.txt
  deploy-version.txt
Labels: enhancement

#155 feature/assets and bugfixes
  SpaceGame/Assets/3D models/Materials/ship.meta
  SpaceGame/Assets/3D models/Materials/ship/arms and details mat.mat
  SpaceGame/Assets/3D models/Materials/ship/arms and details mat.mat.meta
  SpaceGame/Assets/3D models/Materials/ship/main ship mat.mat
  SpaceGame/Assets/3D models/Materials/ship/main ship mat.mat.meta
  SpaceGame/Assets/3D models/ship.fbx
  SpaceGame/Assets/3D models/ship.fbx.meta
  SpaceGame/Assets/3D models/textures/ship.meta
  SpaceGame/Assets/3D models/textures/ship/ship LP_arms and details material_BaseColor.png
  SpaceGame/Assets/3D models/textures/ship/ship LP_arms and details material_BaseColor.png.meta
  SpaceGame/Assets/3D models/textures/ship/ship LP_arms and details material_Emissive.png
  SpaceGame/Assets/3D models/textures/ship/ship LP_arms and details material_Emissive.png.meta
  SpaceGame/Assets/3D models/textures/ship/ship LP_arms and details material_Metallic.png
  SpaceGame/Assets/3D models/textures/ship/ship LP_arms and details material_Metallic.png.meta
  SpaceGame/Assets/3D models/textures/ship/ship LP_arms and details material_Normal.png
  SpaceGame/Assets/3D models/textures/ship/ship LP_arms and details material_Normal.png.meta
  SpaceGame/Assets/3D models/textures/ship/ship LP_arms and details material_Roughness.png
  SpaceGame/Assets/3D models/textures/ship/ship LP_arms and details material_Roughness.png.meta
  SpaceGame/Assets/3D models/textures/ship/ship LP_main ship Material_BaseColor.png
  SpaceGame/Assets/3D models/textures/ship/ship LP_main ship Material_BaseColor.png.meta
  SpaceGame/Assets/3D models/textures/ship/ship LP_main ship Material_Metallic.png
  SpaceGame/Assets/3D models/textures/ship/ship LP_main ship Material_Metallic.png.meta
  SpaceGame/Assets/3D models/textures/ship/ship LP_main ship Material_Normal.png
  SpaceGame/Assets/3D models/textures/ship/ship LP_main ship Material_Normal.png.meta
  SpaceGame/Assets/3D models/textures/ship/ship LP_main ship Material_Roughness.png
  SpaceGame/Assets/3D models/textures/ship/ship LP_main ship Material_Roughness.png.meta
  SpaceGame/Assets/Prefabs/GameObjects/ship.prefab
  SpaceGame/Assets/Prefabs/GameObjects/ship.prefab.meta
  SpaceGame/Assets/Scenes/ModelTesting scene.unity
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerController.cs
  SpaceGame/Assets/WebGLTemplates/PrototypeTemplate/index.html
  SpaceGame/deploy-version.txt
  SpaceGame/web-build/deploy-version.txt
  deploy-version.txt
Labels: WIP, bug, enhancement

#157 bugs and buoys
  SpaceGame/Assets/Imports/Models.meta
  SpaceGame/Assets/Prefabs/GameObjects/Station with drop off.prefab
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/UI/radial Fill/radialMat.mat
  SpaceGame/deploy-version.txt
  SpaceGame/web-build/deploy-version.txt
  deploy-version.txt
Labels: bug, enhancement

#164 fixed the feedback interaction & the config fetch
  SpaceGame/Assets/Scripts/FSM/FeedbackState.cs
  SpaceGame/Assets/Scripts/FSM/FeedbackView.cs
  SpaceGame/Assets/Scripts/Tools/WebConfigHandler.cs
Labels: bug

#171 muted the ost by default, also fixed the visibility of the filled-buoy text
  SpaceGame/Assets/Scenes/SampleScene.unity
Labels: bug, enhancement

#181 added the ability to spawn obstacles in the death-zone
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/Debris/VoronoiDebrisGen.cs
Labels: enhancement

#184 fixed cargo vis and moved files to proper locations
  SpaceGame/Assets/Imports/Models.meta
  SpaceGame/Assets/PlayerCargoVisual.cs
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/Debris/BreakApartHandler.cs
  SpaceGame/Assets/Scripts/NPCController.cs
  SpaceGame/Assets/Scripts/NPCController.cs.meta
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerCargoVisual.cs
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerCargoVisual.cs.meta
  SpaceGame/Assets/Scripts/UI/HighScoreDisplay.cs
  SpaceGame/Assets/Scripts/UI/HighScoreDisplay.cs.meta
  SpaceGame/Assets/Scripts/WaypointNavigator.cs
  SpaceGame/Assets/Scripts/WaypointNavigator.cs.meta
  SpaceGame/deploy-version.txt
  SpaceGame/web-build/deploy-version.txt
  deploy-version.txt
Labels: bug

#185 added blinking light
  SpaceGame/Assets/Prefabs/GameObjects/Station with drop off.prefab
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/BlinkyLight.cs
  SpaceGame/Assets/Scripts/BlinkyLight.cs.meta
  SpaceGame/deploy-version.txt
  SpaceGame/web-build/deploy-version.txt
  deploy-version.txt
Labels: bug

#190 Feature/no more endless names
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/FSM/EnterNameState.cs
  SpaceGame/Assets/Scripts/FSM/EnterNameView.cs
Labels: enhancement

#214 feature/fix inventory reset
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/FSM/tutorial/TutorialState.cs
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerCargoVisual.cs
  azure-pipelines.yml
Labels: bug

#215 feature/fix buoy text reset
  SpaceGame/Assets/Scripts/EventHandler.cs
  SpaceGame/Assets/Scripts/FSM/IngameState.cs
  SpaceGame/Assets/Scripts/FSM/tutorial/TutorialState.cs
  SpaceGame/Assets/Scripts/WinCondition.cs
Labels: bug

#218 feature/sounds adjust
  SpaceGame/Assets/Prefabs/GameObjects/asteroids.prefab
  SpaceGame/Assets/Prefabs/GameObjects/satellite 1.prefab
  SpaceGame/Assets/Prefabs/GameObjects/satellite 2.prefab
  SpaceGame/Assets/Scripts/MotherShipCollisionHandler.cs
  SpaceGame/Assets/Scripts/ObstacleCollisionHandler.cs
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerController.cs
  SpaceGame/Assets/Scripts/PlayerScripts/SoundListener.cs
  SpaceGame/Assets/Scripts/Tools/SoundManager.cs
  SpaceGame/Assets/Sounds/Fuel2.mp3
  SpaceGame/Assets/Sounds/Fuel2.mp3.meta
Labels: bug

#220 feature/sound fix
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/MotherShipCollisionHandler.cs
  SpaceGame/Assets/Scripts/PowerUps/PowerUps.cs
  SpaceGame/Assets/Scripts/ResetStation.cs
Labels: bug

#223 feature/moar config
  SpaceGame/Assets/Scripts/BuoyFillUp.cs
  SpaceGame/Assets/Scripts/Debris/TrashCollisionHandler.cs
  SpaceGame/Assets/Scripts/ObstacleCollisionHandler.cs
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerCargo.cs
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerHealth.cs
  SpaceGame/Assets/Scripts/PowerUps/ExtraTimePowerUp.cs
  SpaceGame/Assets/Scripts/Tools/WebConfigHandler.cs
Labels: enhancement

#227 idno what was going on
  SpaceGame/Assets/Scenes/SampleScene.unity
Labels: bug

#224 text now does also display the fill amount if fill = 0 fix#208
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerCargo.cs
Labels: bug

#230 feature/lfs adjust
  .gitattributes
  TemplateData/fullscreen.png
  TemplateData/progressEmpty.Dark.png
  TemplateData/progressEmpty.Light.png
  TemplateData/progressFull.Dark.png
  TemplateData/progressFull.Light.png
  TemplateData/progressLogo.Dark.png
  TemplateData/progressLogo.Light.png
  TemplateData/webgl-logo.png
Labels: bug

#234 Feature/buoy lights rework
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/BlinkyLight.cs
  SpaceGame/Assets/Scripts/BuoyFillUp.cs
Labels: enhancement

#236 Feature/new ost and menu ost
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/AdjustMenuOst.cs
  SpaceGame/Assets/Scripts/AdjustMenuOst.cs.meta
  SpaceGame/Assets/Scripts/BlinkyLight.cs
  SpaceGame/Assets/Scripts/EventHandler.cs
  SpaceGame/Assets/Scripts/FSM/tutorial/TutorialState.cs
  SpaceGame/Assets/Scripts/FuelGaugeRotator.cs
  SpaceGame/Assets/Scripts/FuelGaugeRotator.cs.meta
  SpaceGame/Assets/Scripts/Tools/OstPlayer.cs
  SpaceGame/Assets/Scripts/TransitionOsts.cs
  SpaceGame/Assets/Scripts/TransitionOsts.cs.meta
  SpaceGame/Assets/Sounds/Aviators - Infinity Awaits Us- A Royalty Free OST - 22 Tetanus (Space Mix).mp3
  SpaceGame/Assets/Sounds/Aviators - Infinity Awaits Us- A Royalty Free OST - 22 Tetanus (Space Mix).mp3.meta
  SpaceGame/Assets/Sounds/Aviators - Infinity Awaits Us- A Royalty Free OST - 26 Submenu BGM.mp3
  SpaceGame/Assets/Sounds/Aviators - Infinity Awaits Us- A Royalty Free OST - 26 Submenu BGM.mp3.meta
Labels: enhancement

#249 feature/azure lfs
  README.md
  azure-pipelines.yml
  release.html
Labels: enhancement

#260 made the buoys sway and respond to player collision
  SpaceGame/Assets/BuoySway.cs
  SpaceGame/Assets/BuoySway.cs.meta
  SpaceGame/Assets/Materials/Flame.mat
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/FSM/IngameState.cs
  SpaceGame/Assets/Scripts/MotherShipCollisionHandler.cs
  SpaceGame/Assets/VFX/nebula/primary nebula mat.mat
  SpaceGame/Assets/VFX/nebula/primary nebula mat.mat.meta
  SpaceGame/Assets/VFX/nebula/secondary nebula mat.mat
  SpaceGame/Assets/VFX/nebula/secondary nebula mat.mat.meta
Labels: enhancement

#258 cinematified the final screen
  SpaceGame/Assets/Scripts/GoalReachedHandler.cs
  SpaceGame/Assets/Scripts/ObstacleCollisionHandler.cs
  SpaceGame/Assets/Scripts/PlayerScripts/TimeOutTimer.cs
  SpaceGame/Assets/Scripts/cutsceneStuff/CamWayPointNavigator.cs
  SpaceGame/Assets/Scripts/cutsceneStuff/CinematicController.cs
Labels: enhancement

#267 feature/osk
  SpaceGame/Assets/Prefabs/UI/OSK.prefab
  SpaceGame/Assets/Prefabs/UI/OSK.prefab.meta
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/CustomOsk.cs
  SpaceGame/Assets/Scripts/CustomOsk.cs.meta
  SpaceGame/Assets/Scripts/Tools/DisableInEditor.cs
  SpaceGame/Assets/Scripts/Tools/DisableInEditor.cs.meta
  SpaceGame/Assets/Scripts/thrusterRotator.cs
  SpaceGame/Assets/Scripts/thrusterRotator.cs.meta
Labels: enhancement

#269 added feature to set different scales for Webgl & Standalone for OSK
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/CustomOsk.cs
Labels: enhancement

#275 feature/code cleanup
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/BuoyScripts/BuoyFillUp.cs
  SpaceGame/Assets/Scripts/BuoyScripts/BuoySway.cs
  SpaceGame/Assets/Scripts/BuoyScripts/MotherShipCollisionHandler.cs
  SpaceGame/Assets/Scripts/BuoyScripts/MotherShipHomingDeviceUI.cs
  SpaceGame/Assets/Scripts/Cinematics/CamWayPointNavigator.cs
  SpaceGame/Assets/Scripts/Cinematics/CinematicController.cs
  SpaceGame/Assets/Scripts/CustomOsk.cs
  SpaceGame/Assets/Scripts/Debris/DebrisCollisionLinker.cs
  SpaceGame/Assets/Scripts/Debris/DebrisPickupLinker.cs
  SpaceGame/Assets/Scripts/Debris/TrashCollisionHandler.cs
  SpaceGame/Assets/Scripts/Debris/VoronoiDebrisGen.cs
  SpaceGame/Assets/Scripts/EventHandler.cs
  SpaceGame/Assets/Scripts/EventHandlerDebugger.cs
  SpaceGame/Assets/Scripts/EventHandlerDebugger.cs.meta
  SpaceGame/Assets/Scripts/FSM/GameOverState.cs
  SpaceGame/Assets/Scripts/FSM/HighscoreState.cs
  SpaceGame/Assets/Scripts/FSM/IngameState.cs
  SpaceGame/Assets/Scripts/FSM/IngameView.cs
  SpaceGame/Assets/Scripts/FSM/State.cs
  SpaceGame/Assets/Scripts/FSM/YouWonState.cs
  SpaceGame/Assets/Scripts/FSM/tutorial/TutorialState.cs
  SpaceGame/Assets/Scripts/FSM/tutorial/nextTutorialState.cs
  SpaceGame/Assets/Scripts/FuelDrop.cs
  SpaceGame/Assets/Scripts/GoalReachedHandler.cs
  SpaceGame/Assets/Scripts/NPC/WaypointNavigator.cs
  SpaceGame/Assets/Scripts/ObstacleCollisionHandler.cs
  SpaceGame/Assets/Scripts/PlayerScripts/InventoryFullSound.cs
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerCargo.cs
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerCargoVisual.cs
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerController.cs
  SpaceGame/Assets/Scripts/PlayerScripts/PlayerHealth.cs
  SpaceGame/Assets/Scripts/PlayerScripts/SoundListener.cs
  SpaceGame/Assets/Scripts/SubjectFilters.meta
  SpaceGame/Assets/Scripts/SubjectFilters/PlayerPickUpTrashFilter.cs
  SpaceGame/Assets/Scripts/SubjectFilters/PlayerPickUpTrashFilter.cs.meta
  SpaceGame/Assets/Scripts/SubjectFilters/PlayerTakeDamageFilter.cs
  SpaceGame/Assets/Scripts/SubjectFilters/PlayerTakeDamageFilter.cs.meta
  SpaceGame/Assets/Scripts/Tools/AReset.cs
  SpaceGame/Assets/Scripts/Tools/DestroyOnReset.cs
  SpaceGame/Assets/Scripts/Tools/SoundManager.cs
  SpaceGame/Assets/Scripts/TransitionOsts.cs
  SpaceGame/Assets/Scripts/UI/ScoreUI.cs
  SpaceGame/Assets/Scripts/highscoreCalculation/LerpScore.cs
Labels: enhancement
