Repository Kill-The-Data/NoNameSpecifiedByTeam, pull requests merged in 2020-05, with the labels that each got.

#126 cleaned up the repository and updated the .gitignore
  .gitignore
  SpaceGame/Assets/Imports/highscore.meta
  SpaceGame/Assets/Imports/score.meta
  SpaceGame/Assets/Prefabs/blur prefabs.meta
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/ProjectSettings/QualitySettings.asset
  SpaceGame/Tuesday.20.2020.default.highscore.txt
  SpaceGame/Wednesday.20.2020.default.highscore.txt
  SpaceGame/Wednesday.21.2020.default.highscore.txt
  SpaceGame/alltime.highscore.txt
Labels: enhancement

#127 cleaned up scene
  SpaceGame/Assets/Scenes/SampleScene.unity
Labels: enhancement

#128 main menu now displays highscore, fixed stuff about scaling with scaling
  SpaceGame/Assets/Prefabs/UI/Highscore.meta
  SpaceGame/Assets/Prefabs/UI/Highscore/AllTimeHighscoreView.prefab
  SpaceGame/Assets/Prefabs/UI/Highscore/AllTimeHighscoreView.prefab.meta
  SpaceGame/Assets/Prefabs/UI/Highscore/DailyHighscoreView.prefab
  SpaceGame/Assets/Prefabs/UI/Highscore/DailyHighscoreView.prefab.meta
  SpaceGame/Assets/Prefabs/UI/Highscore/Score layout group.prefab
  SpaceGame/Assets/Prefabs/UI/Highscore/Score layout group.prefab.meta
  SpaceGame/Assets/Prefabs/UI/HighscoreContainer.prefab
  SpaceGame/Assets/Prefabs/Views.prefab
  SpaceGame/Assets/Prefabs/Views.prefab.meta
  SpaceGame/Assets/Prefabs/blur prefabs.meta
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/FSM/HighscoreState.cs
  SpaceGame/Assets/Scripts/FSM/HighscoreView.cs
  SpaceGame/Assets/Scripts/FSM/IngameState.cs
  SpaceGame/Assets/Scripts/FSM/MainMenuState.cs
  SpaceGame/Assets/Scripts/HighScoreDisplay.cs
  SpaceGame/Assets/Scripts/HighScoreDisplay.cs.meta
  SpaceGame/Assets/Scripts/LerpScoreView.cs
  SpaceGame/Assets/Scripts/MotherShipCollisionHandler.cs
  SpaceGame/Assets/Scripts/lerpScoreView.cs.meta
Labels: WIP, enhancement

#133 adjusted Credits screen to match the new look & feel and also made it work again
  SpaceGame/Assets/Prefabs/FSM/Credits screen.prefab
  SpaceGame/Assets/Prefabs/FSM/GameOverView.prefab
  SpaceGame/Assets/Prefabs/FSM/StartView.prefab
  SpaceGame/Assets/Prefabs/UI/Back.prefab
  SpaceGame/Assets/Prefabs/UI/Back.prefab.meta
  SpaceGame/Assets/Prefabs/UI/Black Border.prefab
  SpaceGame/Assets/Prefabs/UI/Black Border.prefab.meta
  SpaceGame/Assets/Prefabs/Views.prefab
  SpaceGame/Assets/Scripts/FSM/CreditsState.cs
  SpaceGame/Assets/Scripts/FSM/CreditsState.cs.meta
  SpaceGame/Assets/Scripts/FSM/MainMenuState.cs
  SpaceGame/deploy-version.txt
  SpaceGame/web-build/deploy-version.txt
  deploy-version.txt
Labels: enhancement

#134 removed a source of endless agony
  SpaceGame/Assets/Scripts/MotherShipHomingDeviceUI.cs
  SpaceGame/Assets/Scripts/Tools/QuaternionIsNanExt.cs
Labels: bug, enhancement

#144 made the amount of trash automatically correspond to how much should be generated
  SpaceGame/Assets/Scenes/SampleScene.unity
  SpaceGame/Assets/Scripts/BuoyFillUp.cs
  SpaceGame/Assets/Scripts/Debris/VoronoiDebrisGen.cs
Labels: WIP, bug, enhancement
